/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import busSeat.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Date;
import java.text.SimpleDateFormat;
/**
 *
 * @author vasan12sp
 */
public class addService extends javax.swing.JFrame {

    /**
     * Creates new form addService
     */
    public addService() {
        initComponents();
        jDateChooser1.getJCalendar().setMinSelectableDate(new Date());
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/busbooking","root","");
            Statement st = con.createStatement();
            String q = "select busid from busdetails";
            ResultSet rs=st.executeQuery(q);
            while(rs.next()){
                String id=rs.getString("busid");
                jComboBox1.addItem(id);
            }
            con.close();
            
        }catch(Exception e){
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"Exception Occured");
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 255));
        jLabel1.setText("ADD SERVICE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("SELECT BUS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 145, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(0, 51, 51));
        jComboBox1.setForeground(new java.awt.Color(153, 255, 255));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 142, 214, 42));

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 255));
        jLabel3.setText("DATE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 211, -1, -1));

        jDateChooser1.setBackground(new java.awt.Color(0, 51, 51));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 203, 214, 38));

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 255, 255));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 255, 255));
        jButton2.setText("GO BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 51, 51));
        jButton3.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 255, 255));
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solid6.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 650, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new adminOptions().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String selected = (String) jComboBox1.getSelectedItem();
        Date date1=jDateChooser1.getDate();
        SimpleDateFormat dateFormat=new SimpleDateFormat("dd-MM-YYYY");
        
        String date=dateFormat.format(date1);
        try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/busbooking", "root", "");
    Statement st = con.createStatement();
    String q = String.format("select * from busdetails where busid='%s'", selected);
    ResultSet rs = st.executeQuery(q);
    String id = "", start = "", end = "",time="";
    int leftrow = 0, spl = 0, rightrow = 0, spr = 0;

    rs.next();
        id = rs.getString("busid");
        start = rs.getString("start");
        end = rs.getString("end");
        time=rs.getString("time");
        leftrow = rs.getInt("leftrow");
        spl = rs.getInt("spl");
        rightrow = rs.getInt("rightrow");
        spr = rs.getInt("spr");
    
        System.out.println(leftrow);
        System.out.println(spl);
        System.out.println(rightrow);
        System.out.println(spr);
        
        String q2=String.format("insert into servicelist(busid,date,time,start,end) values('%s','%s','%s','%s','%s')",id,date,time,start,end);
        st.executeUpdate(q2);

    // Calculate 'total' after fetching the database values
    int total = (leftrow * spl) + (rightrow * spr);
    String position="",part="";
    for(int i=1;i<=total;i++){
        if(spl==2 && spr==2){
            if(i%2==1 && i<=(leftrow*spl)){
                position="Window";
                part="Left";
            }else if(i%2==0 && i<=(leftrow*spl)){
                position="Side";
                part="Left";
            }else if(i%2==1 && i>(leftrow*spl)){
                position="Window";
                part="Right";
            }else if(i%2==0 && i>(leftrow*spl)){
                position="Side";
                part="Right";
            }
        }else if(spl==3 && spr==2){
            if(i%3==1 && i<=(leftrow*spl)){
                position="Window";
                part="Left";
            }else if(i%3==2 && i<=(leftrow*spl)){
                position ="Middle";
                part="Left";
            }else if(i%3==0 && i<=(leftrow*spl)){
                position="Side";
                part="Left";
            }else if(i%2==1 && i>(leftrow*spl)){
                position="Window";
                part="Right";
            }else if(i%2==0 && i>(leftrow*spl)){
                position="Side";
                part="Right";
        }
    }else if(spl==2 && spr==3){
        if(i%2==1 && i<=(leftrow*spl)){
            position="Window";
            part="Left";
        }else if(i%2==0 && i<=(leftrow*spl)){
            position="Side";
            part="Left";
        }else if(i%3==1 && i>(leftrow*spl)){
                position="Window";
                part="Right";
            }else if(i%3==2 && i>(leftrow*spl)){
                position ="Middle";
                part="Right";
            }else if(i%3==0 && i>(leftrow*spl)){
                position="Side";
                part="Right";
            }
    }
        String qToInsert=String.format("insert into services (busid, date, time, start, end, seat,part,position, passenger, age, id,mobileno) values('%s', '%s','%s','%s','%s', '%d', '%s','%s','', 0, '','')", id, date, time, start, end, i,part,position);
        st.executeUpdate(qToInsert);
        
    }
    
    JOptionPane.showMessageDialog(this, "Service Added Successfully");
        this.setVisible(false);
        new adminOptions().setVisible(true);
        
    con.close();

} catch (Exception e) {
//    e.printStackTrace(); // Print the exception for debugging
    System.out.println(e);
    JOptionPane.showMessageDialog(this, "Exception Occurred");
}

        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
