/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author vasan12sp
 */
public class adminOptions extends javax.swing.JFrame {

    /**
     * Creates new form adminOptions
     */
    public adminOptions() {
        initComponents();
        buttonGroup1.add(addbus);
        buttonGroup1.add(viewbus);
        buttonGroup1.add(removebus);
        buttonGroup1.add(editbus);
        buttonGroup1.add(addservice);
        buttonGroup1.add(editservice);
        buttonGroup1.add(addcity);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        addbus = new javax.swing.JRadioButton();
        viewbus = new javax.swing.JRadioButton();
        removebus = new javax.swing.JRadioButton();
        editbus = new javax.swing.JRadioButton();
        addservice = new javax.swing.JRadioButton();
        editservice = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        addcity = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("DejaVu Sans", 1, 10)); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 255));
        jLabel1.setText("ADMINISTRATOR OPTIONS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        addbus.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        addbus.setForeground(new java.awt.Color(153, 255, 255));
        addbus.setText("ADD BUS");
        getContentPane().add(addbus, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        viewbus.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        viewbus.setForeground(new java.awt.Color(153, 255, 255));
        viewbus.setText("VIEW BUS LIST");
        getContentPane().add(viewbus, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        removebus.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        removebus.setForeground(new java.awt.Color(153, 255, 255));
        removebus.setText("REMOVE BUS");
        getContentPane().add(removebus, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        editbus.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        editbus.setForeground(new java.awt.Color(153, 255, 255));
        editbus.setText("EDIT BUS");
        getContentPane().add(editbus, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        addservice.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        addservice.setForeground(new java.awt.Color(153, 255, 255));
        addservice.setText("ADD SERVICE");
        getContentPane().add(addservice, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        editservice.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        editservice.setForeground(new java.awt.Color(153, 255, 255));
        editservice.setText("DELETE SERVICE");
        getContentPane().add(editservice, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 255, 255));
        jButton1.setText("PROCEED");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 255, 255));
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, -1, -1));

        addcity.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        addcity.setForeground(new java.awt.Color(153, 255, 255));
        addcity.setText("ADD SERVICE CITIES");
        addcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcityActionPerformed(evt);
            }
        });
        getContentPane().add(addcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/vasan12sp/Desktop/solid6.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(addbus.isSelected()){
            new addBusinfo().setVisible(true);
            this.setVisible(false);
        }else if(editbus.isSelected()){
            new editBus().setVisible(true);
            this.setVisible(false);
        }else if(viewbus.isSelected()){
            new viewBus().setVisible(true);
            this.setVisible(false);
        }else if(addservice.isSelected()){
            new addService().setVisible(true);
            this.setVisible(false);
        }else if(editservice.isSelected()){
            new editService().setVisible(true);
            this.setVisible(false);
        }else if(addcity.isSelected()){
            new addCities().setVisible(true);
            this.setVisible(false);
        }
        else{
            new deleteBus().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addcityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton addbus;
    private javax.swing.JRadioButton addcity;
    private javax.swing.JRadioButton addservice;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton editbus;
    private javax.swing.JRadioButton editservice;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton removebus;
    private javax.swing.JRadioButton viewbus;
    // End of variables declaration//GEN-END:variables
}
